<?php

return [

    'leadership',
    'communication',
    'teamwork',
    'collaboration',
    'problem solving',
    'critical thinking',
    'analytical thinking',
    'decision making',
    'adaptability',
    'flexibility',
    'creativity',
    'innovation',
    'time management',
    'organization',
    'planning',
    'presentation',
    'negotiation',
    'mentoring',
    'coaching',
    'conflict resolution',
    'customer service',
    'stakeholder management',
    'project management',
    'risk management',
    'attention to detail',
    'research',
    'documentation',
    'multitasking',
    'self motivation',
    'self learning',
    'fast learner',
    'interpersonal skills',
    'emotional intelligence',
    'active listening',
    'strategic thinking',
    'agile',
    'scrum',
    'ownership',
    'accountability',
    'initiative',
    'work ethic'

];